kind: Service
apiVersion: v1
metadata:
  name: backend-service
spec:
  selector:
    app: backend
    deployment: backend-deployment
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8666
    targetPort: 3000