on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  IMAGE: backend

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
          build-args: GITHUB_SHA="$GITHUB_SHA",GITHUB_REF="$GITHUB_REF"

      - name: Test
        uses: addnab/docker-run-action@v3
        with:
          image: "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
          run: |
            yarn test
            yarn lint
